{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monagentjava.fullname" . }}-config
  labels:
    {{- include "monagentjava.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.springProfiles | quote }}
  MONAGENT_RUNTIME_TIMEZONE: UTC
  MONAGENT_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  MONAGENT_ASYNC_QUEUE_CAPACITY: {{ .Values.config.queueCapacity | quote }}
  MONAGENT_ASYNC_WORKER_THREADS: {{ .Values.config.workerThreads | quote }}
  MONAGENT_ASYNC_COLLECTOR_POOL_SIZE: {{ .Values.config.collectorPoolSize | quote }}
  MONAGENT_ASYNC_DISPATCH_INTERVAL_MS: {{ .Values.config.dispatchIntervalMs | quote }}
  MONAGENT_HEALTH_INTERVAL_SECONDS: {{ .Values.config.healthIntervalSeconds | quote }}
  MONAGENT_PROMETHEUS_INTERVAL_SECONDS: {{ .Values.config.prometheusIntervalSeconds | quote }}
  MONAGENT_LOGS_INTERVAL_SECONDS: {{ .Values.config.logsIntervalSeconds | quote }}
  MONAGENT_TRACES_INTERVAL_SECONDS: {{ .Values.config.tracesIntervalSeconds | quote }}
  MONAGENT_KUBERNETES_INTERVAL_SECONDS: {{ .Values.config.kubernetesIntervalSeconds | quote }}
{{- end -}}
