{{- if and .Values.serviceAccount.create .Values.rbac.create .Values.rbac.namespaceScoped -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monagentjava.fullname" . }}-collector
  labels:
    {{- include "monagentjava.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
subjects:
  - kind: ServiceAccount
    name: {{ include "monagentjava.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "monagentjava.fullname" . }}-collector
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
