apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monagentjava.fullname" . }}-secrets
  labels:
    {{- include "monagentjava.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONAGENT_DATASOURCE_URL: {{ .Values.env.datasourceUrl | quote }}
  MONAGENT_DATASOURCE_USERNAME: {{ .Values.env.datasourceUsername | quote }}
  MONAGENT_DATASOURCE_PASSWORD: {{ .Values.env.datasourcePassword | quote }}
  MONAGENT_OLLAMA_BASE_URL: {{ .Values.env.ollamaBaseUrl | quote }}
  MONAGENT_OLLAMA_MODEL: {{ .Values.env.ollamaModel | quote }}
  MONAGENT_NOTIFICATION_CHANNEL_1: {{ .Values.env.notificationChannel1 | quote }}
  MONAGENT_NOTIFICATION_CHANNEL_2: {{ .Values.env.notificationChannel2 | quote }}
